// <auto-generated />
namespace BankOfBIT.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class StoredProcedures : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StoredProcedures));
        
        string IMigrationMetadata.Id
        {
            get { return "201609282021399_StoredProcedures"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
